In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Data Collection and Preprocessing

In [40]:
dataset_df = pd.read_csv('train.csv')

In [19]:
dataset_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
dataset_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
dataset_df['Age'] = dataset_df['Age'].fillna(dataset_df['Age'].mean())

In [22]:
dataset_df = dataset_df.drop(columns='Cabin', axis=1)

In [23]:
print(dataset_df['Embarked'].mode()[0])

S

In [24]:
dataset_df['Embarked'] = dataset_df['Embarked'].fillna(dataset_df['Embarked'].mode()[0])

In [32]:
dataset_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,2
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,2

In [26]:
encoder = LabelEncoder()

In [31]:
dataset_df['Sex'] = encoder.fit_transform(dataset_df['Sex'])
dataset_df['Embarked'] = encoder.fit_transform(dataset_df['Embarked'])

In [33]:
X = dataset_df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Survived'], axis=1)
Y = dataset_df['Survived']

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [35]:
print(X.shape, X_train.shape, X_test.shape)

(891, 7) (712, 7) (179, 7)

# Model Building and Testing

In [36]:
model = LogisticRegression()

In [37]:
model.fit(X_train, Y_train)

LogisticRegression()

In [38]:
training_prediction = model.predict(X_train)
training_accuracy = accuracy_score(Y_train, training_prediction)
print(training_accuracy)

0.8132022471910112

In [39]:
test_prediction = model.predict(X_test)
test_accuracy = accuracy_score(Y_test, test_prediction)
print(test_accuracy)

0.7877094972067039